# Generated by Django 2.2.3 on 2020-02-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_comment_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='readmore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_pics')),
                ('heading', models.CharField(max_length=400)),
                ('discription', models.CharField(max_length=500)),
            ],
        ),
    ]
