# Generated by Django 2.2.3 on 2020-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_readmore'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmore',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
